//==============================================================================
// Brief   : NetworkManager DHCP6Config interface adaptor
// Authors : André Prata <andreprata@av.it.pt>
//------------------------------------------------------------------------------
// ODTONE - Open Dot Twenty One
//
// Copyright (C) 2009-2012 Universidade Aveiro
// Copyright (C) 2009-2012 Instituto de Telecomunicações - Pólo Aveiro
//
// This software is distributed under a license. The full license
// agreement can be found in the file LICENSE in this distribution.
// This software may not be copied, modified, sold or distributed
// other than expressed in the named license agreement.
//
// This software is distributed without any warranty.
//==============================================================================

/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__DHCP6Config_adaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__DHCP6Config_adaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {
namespace NetworkManager {

class DHCP6Config_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

	DHCP6Config_adaptor()
	: ::DBus::InterfaceAdaptor("org.freedesktop.NetworkManager.DHCP6Config")
	{
		bind_property(Options, "a{sv}", true, false);
	}

	::DBus::IntrospectedInterface *introspect() const 
	{
		static ::DBus::IntrospectedArgument PropertiesChanged_args[] = 
		{
			{ 0, "a{sv}", false },
			{ 0, 0, 0 }
		};
		static ::DBus::IntrospectedMethod DHCP6Config_adaptor_methods[] = 
		{
			{ 0, 0 }
		};
		static ::DBus::IntrospectedMethod DHCP6Config_adaptor_signals[] = 
		{
			{ "PropertiesChanged", PropertiesChanged_args },
			{ 0, 0 }
		};
		static ::DBus::IntrospectedProperty DHCP6Config_adaptor_properties[] = 
		{
			{ "Options", "a{sv}", true, false },
			{ 0, 0, 0, 0 }
		};
		static ::DBus::IntrospectedInterface DHCP6Config_adaptor_interface = 
		{
			"org.freedesktop.NetworkManager.DHCP6Config",
			DHCP6Config_adaptor_methods,
			DHCP6Config_adaptor_signals,
			DHCP6Config_adaptor_properties
		};
		return &DHCP6Config_adaptor_interface;
	}

public:

	/* properties exposed by this interface, use
	 * property() and property(value) to get and set a particular property
	 */
	::DBus::PropertyAdaptor< std::map< std::string, ::DBus::Variant > > Options;

public:

	/* methods exported by this interface,
	 * you will have to implement them in your ObjectAdaptor
	 */

public:

	/* signal emitters for this interface
	 */
	void PropertiesChanged(const std::map< std::string, ::DBus::Variant >& arg1)
	{
		::DBus::SignalMessage sig("PropertiesChanged");
		::DBus::MessageIter wi = sig.writer();
		wi << arg1;
		emit_signal(sig);
	}

private:

	/* unmarshalers (to unpack the DBus message before calling the actual interface method)
	 */
};

} } } 
#endif //__dbusxx__DHCP6Config_adaptor_h__ADAPTOR_MARSHAL_H
